sites = \
{'nagiosServer': {'alias': u'nagiosServer',
                'disable_wato': True,
                'disabled': False,
                'insecure': False,
                'multisiteurl': '',
                'persist': False,
                'socket': 'tcp:nagiosserver:6557',
                'status_host': None,
                'timeout': 10,
                'user_login': True},
 'local': {'alias': u'local',
           'disable_wato': True,
           'disabled': False,
           'insecure': False,
           'multisiteurl': '',
           'persist': False,
           'status_host': None,
           'timeout': 10,
           'user_login': True}}
